import { PlusIcon } from "lucide-react";
import { SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import React from "react";
import ProfilePic from "../../assets/profile/profile-pic.png";
import ProfilePost from "../../assets/page-bodies/pic-post.png";
import DiscussionIcon from "../../assets/page-bodies/discussion-icon.png";
import QuestionIcon from "../../assets/page-bodies/question-icon.png";
import SurveyIcon from "../../assets/page-bodies/survey-icon.png";
import Reactions from "../../assets/page-bodies/reactions.png";
import { ThumbsUp } from "lucide-react";
import { MessageCircle } from "lucide-react";
import { Share } from "lucide-react";